### ISSUE TITLE
Schematic Folder Location

### ISSUE THREAD

**Issue by drkshrk** [TheKye/Eco-WorldEdit#10]
Does it make sense to move the "Schematics" folder from ../Schematics to ../Configs/Mods/WorldEdit/Schematics instead of the base directory like other mods so that hosting providers don't block access?

**Comment by drkshrk** [comment]
also might make sense to force the names to lowercase

**Comment by TheKye** [comment]
forcing names to be lowercase may cause issues with overriding previous files

**Comment by TheKye** [comment]
folder location has been moved as well as a few other things sorted out in development :) will have a new development release soon

**Comment by TheKye** [comment]
Folder location should be set with a few things in mind:

The Server providers and how some of their tools interact with the eco folders, 

The location should also be relevant to the type of file,

Some server providers seem to also limit the ability to create new folders in the parent directory, 

do we have some ideas?

**Comment by Tavren** [comment]
Speaking of type the best is `Storage\Schematics`
Current location was changed to `Mods\UserCode\WorldEdit\Schematics` as this folder should be fully accessed
@StallEF can provide more info about game hosting
There was be also suggestion from @StallEF  to make the config where admins can change location to desired for they server

**Comment by TheKye** [comment]
i think Storage\Schematics will probably be the best place to go

**Comment by Tavren** [comment]
Storage\Schematics from 2.0.1
