### ISSUE TITLE
[Development] Import not working when copying from a different server or after a world wipe.

### ISSUE THREAD

**Issue by drkshrk** [TheKye/Eco-WorldEdit#11]
![image](https://user-images.githubusercontent.com/2175749/118371893-a2648180-b57c-11eb-9a5f-74871196c4e1.png)

Both server running development version of worldedit.

Verified that after I wipe the world same error comes up when trying to import a schematic that was generated by same server.

**Comment by drkshrk** [comment]
maybe this is a permission thing? i will check that too

**Comment by StallEF** [comment]
it problem was and in Eco  version 8 too, mod used SLG save metod what changed very often and even depends on the version of the operating system.

**Comment by TheKye** [comment]
Thanks to the Latest Work from Tavren, This issue should be resolved, however supporting older versions of the plugin will not be possible given the unreliability of the original serializer used
