### ISSUE TITLE
[Version] Compatible with ECO 8

### ISSUE THREAD

**Issue by Tavren** [TheKye/Eco-WorldEdit#14]
Probably would be handy?

**Comment by TheKye** [comment]
the biggest issue we would be facing is that there where core changes in 9.0 which means some of the things we use won't work in 8.0, 9.4 also changes a bunch of core things which might make this be not compatible pre 9.4 but we could keep schematics as supported seeing as they use a custom format this makes keeping schematics supported from older versions easier

**Comment by Tavren** [comment]
yes that correct.
as how i see that is to create a branch and change the current version to work with Eco 8 and that branch probably not going to update further than the release for Eco 8.
The goal here is to allow users to export they creations in Eco 8 and use them in Eco 9 and later as the existing version for Eco 8 work with the EcoSerializer and not allow to use any exported creations on different servers or in the new versions

**Comment by TheKye** [comment]
ahh yes i understand, thats a pretty good idea,

**Comment by StallEF** [comment]
due to the closure of the master server for games earlier than version 11, the development of this solution for the mod is no longer relevant.
