### ISSUE TITLE
[Version] Prepare for ECO 9.4.0

### ISSUE THREAD

**Issue by Tavren** [TheKye/Eco-WorldEdit#15]
We should prepare for it soon

**Comment by StallEF** [comment]
@TheKye  execution commands on Staging 9.4 has problems, can you see what was change in source code pls ?

**Comment by TheKye** [comment]
9.4 Prepwork has been done, just needs to be tested and confirmed working before proceeding

**Comment by StallEF** [comment]
Test on EcoPC_v0.9.4.0-beta-staging-1989 Done

**Comment by StallEF** [comment]
test on v0.9.4.0-beta-staging-2036 - Done
