### ISSUE TITLE
Commands description

### ISSUE THREAD

**Issue by Tavren** [TheKye/Eco-WorldEdit#16]
Not all commands have description in game, should be fixed so `/we` or `/worldedit` commands prints readable list
README needs update for list of commands and arguments, probably it need better formatting.
Would be good to localize WorldEdit.

**Comment by TheKye** [comment]
Localization could be handled through something like Crowdin or even a google spreadsheet

**Comment by StallEF** [comment]
> Localization could be handled through something like Crowdin or even a google spreadsheet
use Crowdin is very good if it will be have autoupdate to github only
github can correct work with csv in repository too

**Comment by StallEF** [comment]
https://github.com/marketplace/actions/crowdin-action

**Comment by StallEF** [comment]
Preliminary testing is complete, both for static strings and with variables {0}

**Comment by StallEF** [comment]
Crowdin "Micro" plan price - $16 per month and I don't think this is a fair price.

**Comment by StallEF** [comment]
add description for command:
- stack
- move
- grow
