### ISSUE TITLE
[QoL] /distr command refactoring

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#18]
- [x] show result in InfoPanel 
- [x] add icons for blocks in list
- [x] use localization blocks names in list
- [x] add information about full space in selection
- [x] add parameret for save txt with result

**Comment by TheKye** [comment]
Changes in regard to this can be found in dev branch

**Comment by StallEF** [comment]
@TheKye icons not work we must use without "Block" in name and Ores have space in name now
![2021-05-27 (1)](https://user-images.githubusercontent.com/26339332/119880834-51b63680-bf35-11eb-8c9a-543eedc50948.png)

**Comment by StallEF** [comment]
I suggest changing the template to =>  <ecoicon item='Blockname'> Blockname - count (%)

**Comment by TheKye** [comment]
alright will have a look today

**Comment by Tavren** [comment]
changed command, now takes arg string (optional) `brief` or `b` and `detail` or `d` also understand `details` `detailed`
full output:
![изображение](https://user-images.githubusercontent.com/6377052/119980736-604c2e80-bfc5-11eb-9328-cd92da51c26a.png)

brief (default):
![изображение](https://user-images.githubusercontent.com/6377052/119980809-7954df80-bfc5-11eb-9a38-e563c6057136.png)

**Comment by StallEF** [comment]
have not localisation sctings:
1) Empty blocks: {0}
2) Total blocks: {0)
