### ISSUE TITLE
No interaction with trees

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#19]
explore the issue of detecting and interacting with trees
(trees have script in model for interacting)

**Comment by Tavren** [comment]
Now fully supported trees, import/export, cleaning with `/del`, undone with `/undo` and cleaning when on the way of `/set` command

**Comment by StallEF** [comment]
commands work well: /set /del /undo /move  /export(/import) 

feature:  the thickness of the tree trunk when inserted does not always correspond to the original
