### ISSUE TITLE
[QoL] increasing the usability of command /import

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#21]
if player did error in import name Plugin must show files list what can be import
files list must show information from files

- [x] add player name, steam id and SLG name to the EcoBlueprint as separate section AuthorInformation
- [x] keep it after import file and provide for exporting, overwrite with copy+export
- [x] handle files without information as Unowned
- [x] show list of files in the infopanel (name, creation date, filesize, eco version, author)

**Comment by TheKye** [comment]
showing information from a file might be tricky, 

What we could do is allow for a description on export and when doing import it could bring up the list of available imports with their description?

**Comment by TheKye** [comment]
Having ui access for this would be heaps better but not really achievable at this time

**Comment by Tavren** [comment]
This can be done:

- Printing list of file names (probably with description if we going to allow add it) and Eco Version file was created (it exist in `.ecobp` file)
- Can show file creation date, size, can count blocks/plants/objects in the file

We can show it:

- In chat
- In InfoPanel (same as the `/distr`?)

**Comment by TheKye** [comment]
info panel is probably cleaner as it can all be managed in a single place rather then in the chat as if its a larger server the info can get lost pretty quick, but overall i like the idea of showing creation date, size, etc, maybe we can attach the eco player name as well? this could also be counter intuitive as someone may just import and export to have their name on it

**Comment by Tavren** [comment]
> maybe we can attach the eco player name as well?

was think about that too, and probably we should, that would be handy, probably we can add all information include SLG name and steam ID - that in future help identify file author on the website by reading it. Question is the user security but player name should be fine in any case.

> this could also be counter intuitive as someone may just import and export to have their name on it

that can happen yes... probably we can handle that as after importing the name can be stored and provided for the export, if the copy perform it clear the name from the import

**Comment by StallEF** [comment]
save author steam/SLG ID need for Dennis what he can identify real author if will be precedents on the forum

**Comment by TheKye** [comment]
i don't think it will matter too much about the forum as the files most likely won't be listed on there, it would cause too much clutter, thats why i planned to make a web archive for it :)

**Comment by Tavren** [comment]
- [ ] add player name, steam id and SLG name to the EcoBlueprint as separate section AuthorInformation
- [ ] keep it after import file and provide for exporting, overwrite with copy+export
- [ ] handle files without information as Unowned
