### ISSUE TITLE
[QoL] add commands for select claim

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#23]
add new commands:
- [x] /we selclaim (/selclaim) - select current claim here stand player on ground level
- [x] /we addclaim (/addclaim) - add current claim here stand player to select before
- [x] /we expclaim (/expclaim) - expands to nearby claim in provided or looking direction

these commands will greatly simplify the life of players using command /walls search claim borders and road builders

**Comment by Tavren** [comment]
@StallEF :  commands should select 1/4 of chunk (5x5) area with Y at -1 from player position

**Comment by StallEF** [comment]
new commands work well
