### ISSUE TITLE
Error in command /paste with fuel storage

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#27]
![2021-05-31](https://user-images.githubusercontent.com/26339332/120241454-72e79180-c26b-11eb-90a4-4c01d40c91c0.png)

**Comment by Tavren** [comment]
Problem was be that export done with increased stack sizes and import performed without this changes on another server.
Fixed paste aborts on trying fit stacks, shows error to player and trying to fix stack to max size.

![20210601120756_1](https://user-images.githubusercontent.com/6377052/120298941-2fc10900-c2d3-11eb-9193-2c9b6ebea52e.jpg)

**Comment by StallEF** [comment]
import work with modify stack size but in game console have WARN
![warn](https://user-images.githubusercontent.com/26339332/120442276-1630c780-c38e-11eb-8b2a-a4d59047f743.png)
