### ISSUE TITLE
Treasury not removed by undo

### ISSUE THREAD

**Issue by MonzUn** [TheKye/Eco-WorldEdit#45]
Eco Version: 9.3.6
Plugin Version: 2.0.1

STR:
1. Move 20 blocks underground (may not be needed).
2. Import attached schematic.
3. Execute the undo command.
4. Observe that the treasury object in the schematic has not been removed by the undo command.

[ShadowGV.zip](https://github.com/TheKye/Eco-WorldEdit/files/6796924/ShadowGV.zip)

**Comment by Tavren** [comment]
While testing we not able to reproduce the problem, Treasure after paste are clearing with undo.
In 2.0.2 we fix few issues related to game objects, so that may fix this problem too.
Try update to latest version of World Edit and if the issue is still there, reopen the ticket with new information.
