### ISSUE TITLE
How to /set ashpalt roads?

### ISSUE THREAD

**Issue by BenjaminHoegh** [TheKye/Eco-WorldEdit#49]
How do you use the /set command to make asphalt roads? when using the name of the block it spawn the inventory version of it

**Comment by TheKye** [comment]
Hi there! 

Asphalt is a very Particular Block when it comes to the Set or Replace Commands

You need to Specify the Block Fully, 

EX:
Asphalt Concrete Cube
Asphalt Concrete White Cube
Asphalt Concrete White Line
Asphalt Concrete White Dash Line
Asphalt Concrete White Edge

There is many others and im not going to list them all at this time, but you can find all the names of the different blocks here: ServerInstallLocation/Mods/__Core__/AutoGen/Forms/Asphalt.cs
