### ISSUE TITLE
Expanding /setpos1 and /setpos2

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#50]
Expanding the functionality of chat commands /setpos1 and /setpos2

1) add arguments for coordinates (x,y,z)
2) if arguments empty to use player coordinates how in old version

description: the player can have a detailed construction scheme and he can set any coordinate on his own without tools or moving around the map.

**Comment by Tavren** [comment]
Commands /setpos1 and /setpos2 now accept XYZ coordinates and set positions to them, if no coordinates given use player position (as before)
