### ISSUE TITLE
[Eco 9.4.5] wrong door animation direction

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#53]
after insertion, the doors are rotated correctly, but the animation always works in one direction

**Comment by Tavren** [comment]
`Mods\__core__\Objects\DoorObject.cs`
doors have a 2 way to open and in code represented by boolean, the problem that it autodetects when spawn to how it will open based on player position.
Field have private setter and no setter method provided so we can't change what side door should open
`public bool OpensOut { get; private set; }`

**Comment by Tavren** [comment]
Not elegant way but fix issue with doors, they now save how they opens and if extension file exist, restore the value.
If no extension file loaded or door information not was stored in blueprint, they act the old default way
