### ISSUE TITLE
add blueprint info reader utility or export info command

### ISSUE THREAD

**Issue by Dwezer** [TheKye/Eco-WorldEdit#57]
Please add command or utility that can show or export to txt blueprint info like
1) dimensions (x,y,z)
2) block types and amounts
3) Items list (optional)

**Comment by Tavren** [comment]
1. Dimension - there not a problem, it can be saved along with clipboard during `/copy` and passed into `BlueprintInfo` when performing export so at `/import` we know about the dimension. The downside is that old files will not have that information but we probably can scan them to get it
2. and 3. don't see the reason to include that information into each file (and do internal distr when exporting) so probably there need to be a command to retrieve that information from the file and display just like `/distr` doing, can include information about inventories (items in objects).

**Comment by Tavren** [comment]
Add `/binfo <blueprint> <outFile>` command to show or save in `.txt` file information about blueprint
Currently without inventories
