### ISSUE TITLE
Dead wiki links

### ISSUE THREAD

**Issue by Praefator** [TheKye/Eco-WorldEdit#59]
As per title - whenever I click any of the links to visit that wiki page, it doesn't actually load but stays on the [main page](https://github.com/TheKye/Eco-WorldEdit/wiki/).

**Comment by killswitch1984xrt** [comment]
ya same here cannot open any links or nothing

**Comment by StallEF** [comment]
wiki is in work just now

**Comment by StallEF** [comment]
https://github.com/TheKye/Eco-WorldEdit/issues/25
