### ISSUE TITLE
Make an "Standalone Version"  of world edit 

### ISSUE THREAD

**Issue by kikaxan** [TheKye/Eco-WorldEdit#60]
Hi,

 I have a probleme with my save (due to one error when playing (bug) I put an object where it should not)

and when i try to restart server , it make a crash with error : Index was outside the bounds of the array.) 

in (6, 0 ,4) file chunk , but i dont know how to edit it 

because i want to delete the object it cause it , for solving probleme , but with a map editor in mod , we need to start server 

if you can make a standalone version Or tell me how modify the chunk file (6, 0 ,4)
it would be nice

thanks for reading and maybe helping , sorry for my bad english 

i give you if you want the code of error : `[14:42:41.170] [12] [Error] [Eco] Failed to start the server. Exception was Exception: IndexOutOfRangeException
Message:Index was outside the bounds of the array.
Source:System.Private.CoreLib

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Shared.Voxel.HashChunkContainer`1.Set(Vector3i pos, T val)
   at Eco.Shared.Voxel.ChunkGrid`1.AddChunk(TChunk chunk)
   at Eco.World.PersistentChunkPack.ForEachChunk(Action`1 action)
   at Eco.World.PersistentChunkGrid.<Load>b__11_0(PersistentChunkObject obj)
   at Eco.Core.Serialization.DataStore.<>c__DisplayClass45_1`1.<LoadAsync>b__1()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.
Error(s) occurred when loading World (Index was outside the bounds of the array.)`

**Comment by TheKye** [comment]
World Edit itself isn't a "World Editor" per-se, its more a toolset for quick in game modifications to blocks, objects etc, 

World Edit isn't capable of editing save files and editing save files have an extremely high chance of corrupting the save rendering it useless, 

The best way to fix this issue you are having is to load a backup of your world from the Storage/Backups folder

**Comment by kikaxan** [comment]
Hi kye ,
its False ,
due to the same bug, all save (backup and current save) are corrupted, because bug only applie when  you reload savegame. (error position large block  in couche 0 1 and 2 (make object under bedrock) )
after that because dont want to loose the save
i have editing save and load a prefious chunk (1 week before bug) and its worked all object and other chunk is good, and the chunk have object bugs, are "reset".
