### ISSUE TITLE
Store Names, Inventory and Prices are not saved

### ISSUE THREAD

**Issue by AdelgisKnoerr** [TheKye/Eco-WorldEdit#61]
It would help sooooo much if the Stores settings would be saved too in blueprints

**Comment by StallEF** [comment]
Keeping store names and stock is dangerous because Eco has gaps with special characters, and the vanilla store already had issues with mod items.

**Comment by Acionyx** [comment]
bumping issue. we have touched this in discord briefly and it seems like store export/import probably could be an optional feature, maybe enabled behind some flag to make sure it will not break default behaviour. it will be helpful for initial government setups on some servers. could you please take a look and re-evaluate this feature? thank you!

**Comment by Tavren** [comment]
> bumping issue. we have touched this in discord briefly and it seems like store export/import probably could be an optional feature, maybe enabled behind some flag to make sure it will not break default behaviour. it will be helpful for initial government setups on some servers. could you please take a look and re-evaluate this feature? thank you!

Store import and export work in version `2.5.2-rc` https://github.com/TheKye/Eco-WorldEdit/releases/tag/v2.5.2-rc

**Comment by Tavren** [comment]
Should work
