### ISSUE TITLE
Move From Assemblies To Nuget

### ISSUE THREAD

**Issue by TheKye** [TheKye/Eco-WorldEdit#65]
Eco Reference Assemblies are now on Nuget, 

Make the Change from Reference Assemblies to Nuget Package:

https://www.nuget.org/packages/Eco.ReferenceAssemblies

**Comment by StallEF** [comment]
how can Nuget help us with preparation in the new version 2 weeks before the release, if it does not contain Staging?

**Comment by TheKye** [comment]
its more for releases then staging, 

it also is alot less work keeping the assemblies updated for each version
