### ISSUE TITLE
Suggestion: Add /nudge command

### ISSUE THREAD

**Issue by ChickenHacker1** [TheKye/Eco-WorldEdit#66]
Usage:
/nudge 1,0,0
Moves selection by +1 on the X plane

/nudge 0,-5,0
Moves selection by -5 on the Y plane

/nudge 3,-2,0
Moves selection by 3 on the X plane, and -2 on the Y plane

Would be super handy as it's tough to tell where something might paste to

**Comment by TheKye** [comment]
would probably be better to do: 

/nudge PlaneValue, amount

ie:

/nudge x, 1
/nudge y, -5
/nudge x, 2, y, -2, z, 5

all can be achieved in the same command easily enough :)

**Comment by StallEF** [comment]
What problem with use command /shift ? It is Moves selection on amount to set  direction? 
If need move in all 3 directions in one time we can add key to shift command just also.

**Comment by ChickenHacker1** [comment]
Wasn't aware of the /shift command. Thanks I'll check it out.

**Comment by Tavren** [comment]
Probably existing command `/shift` did the job, if not, reopen ticket
