### ISSUE TITLE
[Eco 9.7.0] Mathf in Eco core was rewrite

### ISSUE THREAD

**Issue by StallEF** [TheKye/Eco-WorldEdit#67]
Mathf.Cos , Mathf.Sin , Mathf.Round was remove from core Mathf 

How wrote Ecodev need use netstandard 2.1 for it now!

**Comment by TheKye** [comment]
doesn't seem to be an issue in the code from what i can see, 

I did update to the new reference assembly Nuget Package which is for 9.6.6, could have been an issue with the old "Reference Assemblies" we where using

**Comment by StallEF** [comment]
it about 9.7.0 

in theory need change Mathf to MathF and add using System; in WorldEditBlock.cs

**Comment by TheKye** [comment]
Fixed in 9.7-Beta Branch, Added all things needed to test it
