### ISSUE TITLE
Set command can change the impenetrable block causing bad things.

### ISSUE THREAD

**Issue by drkshrk** [TheKye/Eco-WorldEdit#7]
Impenetrable Stone Block can be removed with the wand causing weird things.  The set command needs a safety in it that if this type of block is selected it doesn't let you change it.

**Comment by TheKye** [comment]
are you using the experimental version or the released version?

**Comment by drkshrk** [comment]
It exists in both that I can tell.  I just updated to the experimental and tested that it still exists as well.

**Comment by Tavren** [comment]
Fixed
