### ISSUE TITLE
[Eco 10] Wand not working

### ISSUE THREAD

**Issue by Tavren** [TheKye/Eco-WorldEdit#76]
After migration to Eco 10, Wand not working, its not want select (highlight) blocks, only selecting plants and left/right click interactions not called at all.

**Comment by StallEF** [comment]
Wand was based on the soil analyzer class which now has a limited list of blocks for interaction.
At the moment, in my opinion, the most suitable for us is an analogue of devtool what can interaction with blocks, plants and WO.
