### ISSUE TITLE
Blueprints uploads

### ISSUE THREAD

**Issue by TheKye** [TheKye/Eco-WorldEdit#9]
Make somewhere for schematics to be uploaded with screenshots and descriptions, 

like an archive kinda thing where people can browse builds, download and upload

- [x]  forum
- [x] mod.io

**Comment by drkshrk** [comment]
that would be awesome!

**Comment by StallEF** [comment]
@TheKye  Dennis gave permission to post schematics on the official forum. I will give more information a little later.

**Comment by StallEF** [comment]
- [ ]  forum
- [ ] mod.io

**Comment by StallEF** [comment]
Blueprints can be upload on official Eco forum now -  https://forum.play.eco/filebase/category-file-list/11
Blueprints can be upload on eco.mod.io too - https://eco.mod.io/?filter=t&tag[]=World+Edit+Blueprint
